# site settings
title: Atlas of Historical County Boundaries
subtitle: by The Newberry Library
email: dis@newberry.org
description: Dr. William M. Scholl Center for American History and Culture
baseurl: "/newberry-county-boundaries"
url: "https://parkerotto.github.io"
author:
street_address: 60 W Walton St
city: Chicago
state: IL
zip_code: 60610
country: United States of America
phone: (312) 943-9090
page_excerpts: true

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 60

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/parkerotto
  House: https://www.newberry.org/
  Google-Plus:
  Instagram: https://www.instagram.com/newberrylibrary/
  LinkedIn: https://www.linkedin.com/company/newberry-library
  Twitter: https://x.com/newberrylibrary
  Facebook: https://www.facebook.com/NewberryLibrary/
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
